name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.1

      - name: Build
        run: CI=false && cd ./server && npm run build-all

      - name: Display Build Results
        run: ls -a

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "simple-forms"
          heroku_email: "dominic.fernandez1023@gmail.com"
          buildpack: "https://github.com/heroku/heroku-buildpack-nodejs.git"
